import type { Metadata } from 'next'

import { Geist, Geist_Mono } from 'next/font/google'

import NextTopLoader from 'nextjs-toploader'

import { Toaster } from '@/components/ui/sonner'
import { TRPCReactProvider } from '@/trpc/react'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
      <body>
        <TRPCReactProvider>
          {children}

          <Toaster richColors position="top-right" />
          <NextTopLoader />
        </TRPCReactProvider>
      </body>
    </html>
  )
}
